### ISSUE TITLE
Ultrasonic C++ example doesn't compile

### ISSUE THREAD

**Issue by PeterMitrano** [wpilibsuite/EclipsePlugins#119] opened 2017-09-18 23:12 UTC
the last line is erroneous, and should be removed. then it is correct

**Comment by JLLeitschuh** [comment] 2017-09-19 17:56
Shouldn't the samples get compiled as part of some test to make sure this sort of thing doesn't happen?

**Comment by PeterMitrano** [comment] 2017-09-19 19:34
Agree, but apparently they don't...

**Comment by AustinShalit** [comment] 2017-09-19 19:56
Duplicate of #106

Take a look at https://github.com/wpilibsuite/allwpilib/pull/569 for the java version.
The C++ version was started in https://github.com/wpilibsuite/allwpilib/commit/9c804c13519dc94e82c6a4dc275153d8149190d0

**Comment by PeterJohnson** [comment] 2017-11-04 17:24
Should be fixed thanks to #142.

**Closed as completed by PeterJohnson** 2017-11-04 17:24 UTC
